### ISSUE TITLE
Implement style preset system for consistent visual themes

### ISSUE THREAD

**Issue by marknorgren** [marknorgren/slide-gen#3]
## Problem

Currently, each user must manually specify theme and style strings, leading to:
- Inconsistent visual results across presentations
- Trial-and-error approach to finding good style combinations
- No curated, high-quality style options
- Difficulty achieving professional-looking results

## Current State

- Manual theme/style specification: `"corporate excellence, growth"` / `"landscape photography, natural lighting"`
- Hard-coded defaults that don't suit all use cases
- No validation or guidance for effective style combinations
- Users must research effective prompt engineering for each provider

## Proposed Solution

Implement a comprehensive style preset system with curated, tested combinations:

### Built-in Style Presets

```yaml
# Corporate/Business Presets
corporate-modern:
  theme: "corporate excellence, innovation, leadership"
  style: "corporate photography, clean aesthetics, professional lighting"
  
corporate-minimal:
  theme: "business strategy, executive presence, growth"
  style: "minimal photography, architectural, geometric composition"

# Academic/Research Presets  
academic-research:
  theme: "scientific discovery, research methodology, academic excellence"
  style: "documentary photography, natural lighting, scholarly atmosphere"

academic-technical:
  theme: "technology innovation, engineering precision, scientific advancement"
  style: "technical photography, industrial design, modern laboratory"

# Creative/Design Presets
creative-modern:
  theme: "innovation, creativity, artistic vision"
  style: "contemporary art, abstract composition, vibrant colors"

creative-minimal:
  theme: "design thinking, aesthetic elegance, creative process"
  style: "minimalist photography, negative space, clean composition"
```

### CLI Integration

```bash
# Use preset instead of manual theme/style
slide-gen --titles "Market Analysis" --preset corporate-modern
slide-gen --file slides.md --preset academic-research

# List available presets
slide-gen --list-presets

# Show preset details
slide-gen --show-preset corporate-modern
```

### Configuration Files

```yaml
# config.yaml - reference preset and optionally override
preset: "corporate-modern"
# Optional overrides
theme: "custom theme override"  
style: "custom style override"
```

### 1. Preset Definition System
- **Location**: `src/slide_gen/presets/` directory
- **Format**: YAML files for each preset category
- **Schema**: theme, style, aspect_ratio, optional provider-specific settings

### 2. Preset Loader
- **New module**: `src/slide_gen/utils/preset_loader.py`
- **Functions**: `load_presets()`, `get_preset()`, `list_presets()`, `validate_preset()`
- **Caching**: Load presets once, cache in memory

### 3. CLI Integration
- **New arguments**: `--preset`, `--list-presets`, `--show-preset`
- **Validation**: Ensure preset exists, show helpful error messages
- **Priority**: CLI theme/style overrides preset values

### 4. Configuration Integration
- **Update**: `DirectoryConfig` to support preset reference
- **Precedence**: explicit theme/style > preset values > defaults

## Benefits

- **Consistency**: Curated combinations ensure high-quality results
- **Ease of use**: Simple preset names vs. complex style strings
- **Discoverability**: Users can explore different visual styles easily
- **Quality**: Tested combinations optimized for each provider
- **Extensibility**: Users can create custom preset files

## Future Extensions

- User-defined custom presets in `~/.slide-gen/presets/`
- Provider-specific preset optimizations
- Industry-specific preset collections
- Community-contributed preset repository

## Testing Strategy

- Generate sample images with each preset
- Visual consistency validation across providers
- Performance testing with preset loading
- CLI integration testing

This feature addresses the core issue of inconsistent styling while maintaining the flexibility of manual configuration.
