### ISSUE TITLE
Add visual consistency mechanisms across slide sets

### ISSUE THREAD

**Issue by marknorgren** [marknorgren/slide-gen#5]
## Problem

Currently, each slide image is generated independently with no visual consistency mechanisms. This results in:
- Inconsistent visual style across slides in the same presentation
- Different color palettes, lighting, and composition between related slides
- Professional presentations that look disjointed
- No way to maintain brand or visual identity across a slide deck

## Current State

- Each image generated with separate API calls
- No shared visual parameters between slides
- No reference image or style seed support
- No mechanism to ensure coherent visual narrative

Example issue: A presentation about "Corporate Strategy" might generate:
1. A forest landscape for "Vision"
2. A mountain peak for "Analysis" 
3. An abstract composition for "Implementation"

These don't feel like they belong to the same presentation.

## Proposed Solution

Implement multiple visual consistency mechanisms:

### 1. Style Seed/Reference System

```bash
# Generate reference image for first slide, use as style guide for others
slide-gen --titles "Vision" "Strategy" "Execution" \
  --preset corporate-modern \
  --style-seed  # Generate consistent style across all slides

# Use existing image as style reference
slide-gen --titles "Q2 Results" "Q3 Forecast" \
  --style-reference ./previous-slide.png
```

### 2. Color Palette Consistency

```yaml
# In config.yaml or preset
color_palette:
  primary: ["#1E3A8A", "#3B82F6"]    # Corporate blues
  secondary: ["#F3F4F6", "#E5E7EB"]  # Neutral grays
  accent: ["#F59E0B"]                # Golden accent

# Or simplified
color_scheme: "corporate-blue"  # Predefined palette
```

### 3. Visual Theme Consistency

```yaml
# Enhanced style parameters
visual_consistency:
  lighting: "golden-hour"           # Consistent lighting across slides
  composition: "rule-of-thirds"     # Consistent framing
  depth_of_field: "shallow"         # Consistent focus style
  color_temperature: "warm"         # Consistent mood
```

### 4. Session-Based Style Memory

```python
# Automatic style consistency within a generation session
# First slide establishes visual baseline
# Subsequent slides maintain visual coherence
session_consistency: true
```

### 1. Enhanced PromptRequest Structure

```python
@dataclass
class PromptRequest:
    # Existing fields...
    
    # New consistency fields
    style_seed: Optional[str] = None
    reference_image: Optional[Path] = None
    color_palette: Optional[Dict[str, List[str]]] = None
    visual_consistency: Optional[Dict[str, str]] = None
    session_style: Optional[Dict[str, Any]] = None
```

### 2. Consistency Engine

- **New module**: `src/slide_gen/consistency/style_consistency.py`
- **Functions**: 
  - `generate_style_seed()`: Create consistent parameters for session
  - `apply_style_consistency()`: Modify prompts for visual coherence
  - `extract_visual_elements()`: Parse successful generation for reuse

### 3. Provider Integration

- **Enhanced prompts**: Include consistency parameters in AI prompts
- **Style transfer**: Use provider-specific techniques for visual consistency
- **Validation**: Check generated images meet consistency requirements

### 4. CLI Integration

```bash
# New CLI options
--style-seed              # Generate consistent style seed
--reference-image PATH    # Use existing image as style reference  
--color-scheme NAME       # Use predefined color palette
--visual-consistency      # Enable automatic session consistency
```

### OpenAI DALL-E
- Use style descriptions and composition guidelines
- Consistent prompt structure across slides
- Color palette keywords in prompts

### Google Gemini/Imagen
- Leverage style transfer capabilities
- Use reference image features if available
- Consistent visual parameters

## Benefits

- **Professional consistency**: Slide decks look cohesive and branded
- **Time savings**: No manual style coordination needed
- **Quality improvement**: Consistent high-quality visual standards
- **Brand compliance**: Maintain corporate visual identity
- **User experience**: Simple options for complex visual requirements

## Future Extensions

- Machine learning-based style analysis
- Brand guideline integration (logo colors, fonts, etc.)
- Advanced color harmony algorithms
- Cross-session style persistence
- Visual style analytics and reporting

## Testing Strategy

- Generate test slide sets with/without consistency
- Visual similarity metrics between slides
- User testing for perceived coherence
- Performance impact measurement

This feature transforms slide-gen from individual image generation to cohesive presentation design.
