### ISSUE TITLE
Expand style categories beyond landscape photography default

### ISSUE THREAD

**Issue by marknorgren** [marknorgren/slide-gen#6]
## Problem

The current system is heavily biased toward \"landscape photography\" as the default style, which severely limits visual variety and appropriateness for different presentation contexts. This results in:

- All slides defaulting to outdoor/nature themes regardless of content
- Inappropriate visual styles for technical, corporate, or abstract topics
- Limited creative expression and visual diversity
- Hard-coded assumptions that don't match user needs

### Hard-coded Landscape Bias

**OpenAI Provider** (`src/slide_gen/providers/openai_provider.py:29`):
```python
system_prompt = '''You are a professional photographer specializing in landscape photography...'''
```

**Default Style** (`src/slide_gen/providers/base.py:15`):
```python
style: str = \"landscape photography, natural lighting\"
```

**Generated Prompts**: Examples from current output show overwhelming landscape focus:
- \"dense forest at dawn, with a lone tree\"
- \"panoramic view from the summit of success\" 
- \"standing at the edge of a majestic mountain peak\"

### Limited Visual Categories

Currently only supports:
- Landscape photography (dominant)
- Corporate photography (basic)
- Documentary photography (academic)

Missing essential categories:
- Abstract/conceptual imagery
- Architectural/geometric
- Illustration/artistic
- Technical/scientific visualization
- Minimalist/design-focused

### 1. Remove Hard-coded Landscape Bias

**Update provider system prompts**:
```python
# Instead of landscape-specific:
system_prompt = '''You are a professional visual content creator specializing in creating compelling background images for presentations...'''

# Instead of default landscape style:
style: str = \"professional photography, appropriate lighting\"
```

### 2. Comprehensive Style Categories

```yaml
# Photography Styles
photography:
  - \"corporate photography, professional lighting\"
  - \"architectural photography, geometric composition\"
  - \"macro photography, detailed textures\"
  - \"street photography, urban environments\"
  - \"studio photography, controlled lighting\"
  - \"documentary photography, natural moments\"

# Illustration Styles  
illustration:
  - \"vector illustration, clean graphics\"
  - \"watercolor illustration, artistic textures\"
  - \"technical illustration, precise diagrams\"
  - \"abstract illustration, conceptual design\"

# Design Styles
design:
  - \"minimal design, negative space\"
  - \"geometric design, pattern-based\"
  - \"gradient design, color transitions\"
  - \"texture design, material focus\"

# Conceptual Styles
conceptual:
  - \"abstract concept, symbolic representation\"
  - \"metaphorical imagery, conceptual thinking\"
  - \"surreal concept, creative interpretation\"
```

### 3. Context-Aware Style Selection

```python
# Intelligent style selection based on slide content
def suggest_style_category(slide_title: str, slide_content: str) -> str:
    \"\"\"Suggest appropriate style category based on content.\"\"\"
    
    # Technical/Data topics → clean, minimal
    if any(word in slide_content.lower() for word in ['data', 'analysis', 'chart', 'metrics']):
        return \"minimal design, data visualization\"
    
    # Strategy/Business topics → corporate, professional  
    if any(word in slide_content.lower() for word in ['strategy', 'business', 'market']):
        return \"corporate photography, professional\"
        
    # Creative/Innovation topics → artistic, conceptual
    if any(word in slide_content.lower() for word in ['innovation', 'creative', 'design']):
        return \"abstract illustration, conceptual design\"
```

### 4. Provider-Specific Style Adaptation

```python
class StyleAdapter:
    \"\"\"Adapt style descriptions for different AI providers.\"\"\"
    
    def adapt_for_provider(self, style: str, provider: str) -> str:
        if provider == \"openai\":
            return self._adapt_for_dalle(style)
        elif provider == \"gemini\":
            return self._adapt_for_imagen(style)
```

### 1. Update Base Classes

- **Remove landscape defaults** from `PromptRequest`
- **Add style category enum** for validation
- **Update provider system prompts** to be style-agnostic

### 2. Style Category System

- **New module**: `src/slide_gen/styles/categories.py`
- **Style registry**: Organized categories with descriptions
- **Style validation**: Ensure coherent style combinations

### 3. Content-Aware Suggestions

- **New module**: `src/slide_gen/styles/content_analyzer.py`  
- **Keyword analysis**: Match content to appropriate styles
- **Machine learning potential**: Future content-based style prediction

### 4. CLI Integration

```bash
# New style category options
slide-gen --titles \"Data Analysis\" --style-category illustration
slide-gen --titles \"Vision Statement\" --style-category conceptual

# List available categories  
slide-gen --list-style-categories

# Show category examples
slide-gen --show-style-category abstract
```

### Before (Landscape-biased)
- \"Market Analysis\" → Mountain peak landscape
- \"Data Visualization\" → Forest with charts overlay
- \"Team Building\" → Hiking trail metaphor

### After (Context-appropriate)
- \"Market Analysis\" → Clean geometric composition with data elements
- \"Data Visualization\" → Minimal design with abstract data patterns  
- \"Team Building\" → Corporate photography with professional interaction

## Benefits

- **Appropriate visuals**: Styles match content context
- **Visual diversity**: Rich variety of presentation aesthetics  
- **Professional quality**: Context-appropriate professional imagery
- **Creative flexibility**: Support for artistic and conceptual presentations
- **User satisfaction**: Images that actually fit their content

## Migration Strategy

- **Backward compatibility**: Existing configs continue working
- **Gradual transition**: New defaults only affect new generations
- **Documentation**: Clear examples of new style categories
- **User education**: Help users discover appropriate styles

This change transforms slide-gen from a landscape-photo generator into a versatile presentation visual tool.
